# Generated by Django 5.1.6 on 2025-02-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_monocycle_monowheel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monowheel',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monowheel',
            name='max_speed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='monowheel',
            name='model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monowheel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='monowheel',
            name='range',
            field=models.FloatField(null=True),
        ),
    ]
