# Generated by Django 5.1.6 on 2025-02-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monocycle',
            new_name='Monowheel',
        ),
    ]
