name: lab2-arhitecture

services:
  postgres-service:
    container_name: postgres-container
    image: postgres:17-alpine
    #environment:
    #  - name=value
    ports:
    - 1024:1024
    env_file:
      - .env
  backend-service:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: dockerfile
    working_dir: /backend
    ports:
      - 8000:8000
    command: "python manage.py migrate && python manage.py runserver"
    depends_on:
      - postgres-service